# Substitutions for reusable variables
substitutions:
  name: esphome-dog-feeder
  friendly_name: dog feeder

# Include other configuration files
packages:
  scoop: !include scoop.yaml
  #schedules: !include schedules.yaml

# ESPHome configuration
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: dogfeeder.esphome
    version: '1.0'
  on_boot:
    priority: 500  # Lower priority than our UI update
    then:
      - logger.log: "reset position!"
      - servo.write: 
          id: my_servo
          level: -100%

# Enable logging for debugging
logger:

# Enable a web server for device monitoring
web_server:

# Enable captive portal for easier Wi-Fi setup
captive_portal:

# Enable Home Assistant API for integration
api:

# Enable Bluetooth Proxy feature
bluetooth_proxy:

# Enable OTA updates for firmware updates
ota:
  # Specify OTA platform
  platform: esphome

# Example configuration entry
servo:
  - id: my_servo
    output: pwm_output
    restore: true  # Add this to remember last position on restart

# Example output platform
# On ESP32, use ledc output
output:
  - platform: ledc
    id: pwm_output
    pin: GPIO27
    frequency: 50 Hz

# Slider configuration for controlling servo position
number:
  - platform: template
    name: "Servo Current Position"
    id: servo_position
    min_value: -100
    max_value: 100
    step: 1
    initial_value: -100
    optimistic: true
    on_value:
      - servo.write:
          id: my_servo
          level: !lambda 'return x / 100.0;'
  # Home Assistant helpers
  - platform: homeassistant
    name: "Servo Target Position"
    id: servo_target
    entity_id: input_number.servo_target
  - platform: homeassistant
    name: "Servo Return Position"
    id: servo_return
    entity_id: input_number.servo_return
  - platform: homeassistant
    name: "Servo Wiggle Threshold"
    id: servo_wiggle
    entity_id: input_number.servo_wiggle_stop
  - platform: homeassistant
    name: "Servo Wiggle Range"
    id: servo_wiggle_range
    entity_id: input_number.servo_wiggle_range
  - platform: homeassistant
    name: "Servo Wiggle Shakes"
    id: servo_wiggle_shakes
    entity_id: input_number.servo_wiggle_shakes

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
