# Substitutions for reusable variables
substitutions:
  name: esphome-dog-feeder
  friendly_name: dog feeder

# Include other configuration files
packages:
  scoop: !include scoop.yaml
  schedules: !include schedules.yaml

# ESPHome configuration
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: dogfeeder.esphome
    version: '1.0'
  on_boot:
    # Wait 10 seconds on boot
    then:
      - logger.log: reset position!
      - servo.write: 
          id: my_servo
          level: -100%

# Enable logging for debugging
logger:

# Enable a web server for device monitoring
web_server:

# Enable captive portal for easier Wi-Fi setup
captive_portal:

# Enable Home Assistant API for integration
api:

# Enable OTA updates for firmware updates
ota:
  # Specify OTA platform
  platform: esphome

# Example configuration entry
servo:
  - id: my_servo
    output: pwm_output
    min_level: -1.0
    max_level: 1.0
    restore: true  # Add this to remember last position on restart

# Example output platform
# On ESP32, use ledc output
output:
  - platform: ledc
    id: pwm_output
    pin: GPIO27
    frequency: 50 Hz
    # Add these for more precise control
    min_power: 0.03  # 3% duty cycle (typical servo min is ~1ms out of 20ms)
    max_power: 0.12  # 12% duty cycle (typical servo max is ~2ms out of 20ms)

# Slider configuration for controlling servo position
number:
  - platform: template
    name: "Servo Position"
    id: servo_position
    # Minimum slider valueue: -100
    step: 1 slider value
    on_value:
      - servo.write: 
          id: my_servo
          level: !lambda ' return x / 100.0;'    optimistic: True

# Sync time with Home Assistant.n_value:
time:
  - platform: homeassistant
    id: homeassistant_time          level: !lambda ' return x / 100.0;'


# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
