# Scheduled feeding times
time:
  - platform: homeassistant
    id: homeassistant_time

# Scheduled feeding automations
automation:
  - id: morning_feed
    description: "Morning feeding time"
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      - lambda: |-
          // For globals, we access directly without .state
          float target = id(quick_servo_target);
          id(servo_position).publish_state(target);
      - delay: 5s
      - lambda: |-
          float return_pos = id(quick_servo_return);
          id(servo_position).publish_state(return_pos);
      
  - id: evening_feed
    description: "Evening feeding time"
    trigger:
      - platform: time
        at: "18:00:00"
    action:
      - lambda: |-
          float target = id(quick_servo_target);
          id(servo_position).publish_state(target);
      - delay: 5s
      - lambda: |-
          float return_pos = id(quick_servo_return);
          id(servo_position).publish_state(return_pos);
