globals:
  - id: quick_servo_target
    type: float
    restore_value: yes  # Change to yes to persist across reboots
    initial_value: '90.0'
  - id: quick_servo_return
    type: float
    restore_value: yes  # Change to yes to persist across reboots
    initial_value: '-90.0'

# Number components for Home Assistant UI
number:
  - platform: template
    name: "Quick Servo Target Position"
    id: quick_servo_target_ui
    min_value: -100
    max_value: 100
    step: 1
    initial_value: 90
    optimistic: false  # Let ESPHome handle the state
    set_action:
      - lambda: |-
          id(quick_servo_target) = x;
          id(quick_servo_target_ui).publish_state(x);  # Update the UI state

  - platform: template
    name: "Quick Servo Return Position"
    id: quick_servo_return_ui
    min_value: -100
    max_value: 100
    step: 1
    initial_value: -90
    optimistic: false  # Let ESPHome handle the state
    set_action:
      - lambda: |-
          id(quick_servo_return) = x;
          id(quick_servo_return_ui).publish_state(x);  # Update the UI state

# Button configuration
button:
  # Button to gradually change the servo position from -100 to 100 and back
  - platform: template
    name: "Gradually Change Servo Position"
    on_press:
      then:
        # Reset position to -100 at the start
        - lambda: |-
            id(servo_position).publish_state(-100.0);
        # Repeat 200 times to increment the position
        - repeat:
            count: 200
            then:
              - lambda: |-
                  // Simplified calculation: just add 1 to current position
                  float position = id(servo_position).state + 1.0;
                  position = std::min(position, 100.0); // Safety check
                  id(servo_position).publish_state(position);
              # Delay to spread over 20 seconds (20s / 200 steps)
              - delay: 50ms
        # Wait for 3 seconds
        - delay: 3s
        # Reset position to 100 before decrementing
        - lambda: |-
            id(servo_position).publish_state(100.0);
        # Repeat 200 times to decrement the position
        - repeat:
            count: 200
            then:
              - lambda: |-
                  // Simplified calculation: just subtract 1 from current position
                  float position = id(servo_position).state - 1.0;
                  position = std::max(position, -100.0); // Safety check
                  id(servo_position).publish_state(position);
              # Delay to spread over 20 seconds (20s / 200 steps)
              - delay: 50ms

  # Button to move servo to target position, wait, and return
  - platform: template
    name: "Move Servo and Return"
    on_press:
      then:
        # Move servo to target position
        - lambda: |-
            float target = id(quick_servo_target);
            // Update the servo position
            id(servo_position).publish_state(target);
        # Wait for 5 seconds
        - delay: 5s
        # Move servo back to return position
        - lambda: |-
            float return_pos = id(quick_servo_return);
            // Update the servo position
            id(servo_position).publish_state(return_pos);

# Initialize UI components with stored values on startup
esphome:
  on_boot:
    priority: 600  # After other components are initialized
    then:
      - lambda: |-
          // Update UI components with stored global values
          id(quick_servo_target_ui).publish_state(id(quick_servo_target));
          id(quick_servo_return_ui).publish_state(id(quick_servo_return));
